#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
#tint2 &

need_dual_monitor=0
today_is_even=$(date | awk '{print $3}' | awk '{print $1 % 2}')

if [[ $need_dual_monitor -eq 0 ]]; then
	/home/terryfung/.screenlayout/home.sh 
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
	bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10
	
	if [[ $today_is_even -eq 0 ]]; then
		nitrogen --random --set-scaled /home/terryfung/.wallpapers/dark
	else

		nitrogen --random --set-scaled /home/terryfung/.wallpapers/light
	fi
fi
# else
# 	/home/terryfung/.config/bspwm/my_monitor
# 	bspc monitor HDMI1 -d 1 2 3 4 5 6 7
# 	bspc monitor eDP1 -d  8 9 10
# 	nitrogen --random --set-scaled --head=0 /home/terryfung/.wallpapers
# 	nitrogen --random --set-scaled --head=1 /home/terryfung/.wallpapers
# fi

bspc config window_gap 15
bspc config border_width 4
bspc config focused_border_color \#5b8a72

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#test
bspc config click_to_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
#bspc config merge_overlapping_monitors true

# wallpaper
#exec feh --bg-scale /home/terryfung/.wallpapers/forest-outline.png

# polybar
/home/terryfung/.config/polybar/launch.sh &

# windows rules
bspc rule -a emacs-27.2 desktop=^1 state=tiled
