#!/bin/bash

laptop_monitor=$(xrandr --query | grep 'eDP1')
external_monitor=$(xrandr --query | grep 'HDMI1')

if [[ $external_monitor = *connected* ]]; then
	xrandr --output eDP1 --mode 1366x768 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
fi
